version: '3.7'

services:
  db:
    image: postgres:15
    restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped

  simplelogin:
    image: simplelogin/app:latest
    restart: unless-stopped
